name: Create and Upload Artifact

on:
  workflow_dispatch

jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional if you don't need repo files)
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a file
      - name: Create test.txt
        run: echo "This is a test file created by GitHub Actions" > test.txt

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: test.txt

  download-test:
    runs-on: ubuntu-latest
    needs: create-and-upload
    steps:
      - name: cat-zero
        run: ls
      # Checkout the repository (optional if you don't need repo files)
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: cat-one
        run: echo "cat-one"; cat test.txt
      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file

      - name: cat-two
        run: echo "cat-two"; ls; cat test.txt
